# Generated by Django 2.2.15 on 2020-10-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='defo', upload_to='images/'),
        ),
    ]
