# Generated by Django 2.2.15 on 2020-10-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201017_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='image',
        ),
    ]
